# Generated by Django 4.2.4 on 2023-11-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0003_alter_profile_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='wishlist',
        ),
        migrations.AddField(
            model_name='profile',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='favourites_in', to='users.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='wishlists',
            field=models.ManyToManyField(blank=True, related_name='wishlists_in', to='products.product'),
        ),
    ]
