# Generated by Django 4.2.4 on 2023-11-01 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_favourite_remove_profile_wishlist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='favourites',
            new_name='favourite',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='wishlists',
            new_name='wishlist',
        ),
    ]
