# Generated by Django 4.2.4 on 2023-11-08 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_dashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='dashboard_user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
