# Generated by Django 4.2.4 on 2023-11-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_post_review_product'),
        ('users', '0008_alter_dashboard_dashboard_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='carts_in', to='products.product'),
        ),
    ]
