# Generated by Django 4.2.4 on 2023-11-11 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cart',
        ),
    ]
