# Generated by Django 4.2.4 on 2023-11-11 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_order_address_alter_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
