# Generated by Django 4.2.4 on 2023-11-29 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_seller'),
        ('users', '0017_remove_order_cart_remove_order_owner_delete_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_products', to='products.product'),
        ),
    ]
