# Generated by Django 4.2.4 on 2023-11-29 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_customuser_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='product',
            new_name='Products',
        ),
    ]
