# Generated by Django 4.2.4 on 2023-11-29 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_rename_product_customuser_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Products',
            new_name='products',
        ),
    ]
