# Generated by Django 4.2.4 on 2023-11-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_seller'),
        ('users', '0020_rename_products_customuser_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='products',
        ),
        migrations.AddField(
            model_name='customuser',
            name='products',
            field=models.ManyToManyField(null=True, related_name='user_products', to='products.product'),
        ),
    ]
