# Generated by Django 4.2.4 on 2024-02-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_seller'),
        ('users', '0021_remove_customuser_products_customuser_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='user_products', to='products.product'),
        ),
    ]
