# Generated by Django 4.2.4 on 2024-03-25 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_customuser_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='products',
        ),
    ]
