# Generated by Django 4.2.4 on 2024-08-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_remove_customuser_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at'),
        ),
        migrations.AddField(
            model_name='profile',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at'),
        ),
    ]
