# Generated by Django 5.1.1 on 2024-10-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_dashboard_dashboard_user_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('BY', 'buyer'), ('SL', 'seller')], default='BY', max_length=20),
        ),
    ]
