# Generated by Django 4.2.4 on 2023-11-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_order_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_option',
            field=models.CharField(blank=True, choices=[('PY', 'Palmpay'), ('OP', 'Opay'), ('MP', 'Moniepoint'), ('UBA', 'UBA'), ('FBN', 'First Bank'), ('GTB', 'GTB')], default='PY', null=True),
        ),
    ]
