# Generated by Django 4.2.4 on 2023-11-20 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_order_payment_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='attended_to',
            field=models.BooleanField(default=False),
        ),
    ]
