# Generated by Django 4.2.4 on 2023-11-28 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0006_cart_ordered_order_attended_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
