# Generated by Django 4.2.4 on 2024-08-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_seller'),
        ('cart', '0007_cartitems_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(related_name='order_in', to='products.product'),
        ),
    ]
