# Generated by Django 4.2.4 on 2024-08-06 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_orderitem_alter_order_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
    ]
