# Generated by Django 4.2.4 on 2024-08-07 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_order_cart_alter_order_order_items_delete_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_items',
        ),
    ]
