# Generated by Django 4.2.4 on 2024-08-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_remove_cart_ordered_cart_time_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='category',
            field=models.TextField(blank=True),
        ),
    ]
