# Generated by Django 4.2.4 on 2024-08-13 15:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_alter_cart_items_alter_cart_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_of_order',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='created_at'),
        ),
    ]
