# Generated by Django 5.1.1 on 2024-10-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_alter_order_time_of_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='category',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_option',
            field=models.CharField(choices=[('PY', 'Palmpay'), ('OP', 'Opay'), ('MP', 'Moniepoint'), ('UBA', 'UBA'), ('FBN', 'First Bank'), ('GTB', 'GTB')], default='PY', max_length=50),
        ),
    ]
