# Generated by Django 4.2.4 on 2023-10-22 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('EL', 'Electronics'), ('AR', 'Arts&Crafts'), ('BE', 'Beauty'), ('CL', 'Clothings'), ('AC', 'Accessories'), ('TY', 'Toys&Games'), ('SP', 'Sports&Outdoor'), ('HP', 'Home Products')], default='EL', max_length=25)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='product_default.png', upload_to='product_pics')),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('listed', models.BooleanField(default=False)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
