# Generated by Django 4.2.4 on 2023-10-13 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product_default.jpg', upload_to='product_pics'),
        ),
    ]
