# Generated by Django 4.2.4 on 2023-11-04 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_review_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='post',
            new_name='product',
        ),
    ]
