# Generated by Django 4.2.4 on 2023-10-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('EL', 'Electronics'), ('A&C', 'Arts&Crafts'), ('BE', 'Beauty'), ('CL', 'Clothings'), ('AC', 'Accesories'), ('T&G', 'Toys&Games'), ('S&O', 'Sports&Outdoor'), ('HP', 'Home Products')], default='EL', max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
