# Generated by Django 4.2.4 on 2023-10-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_category_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('EL', 'Electronics'), ('A&C', 'Arts&Crafts'), ('BE', 'Beauty'), ('CL', 'Clothings'), ('AC', 'Accessories'), ('T&G', 'Toys&Games'), ('S&O', 'Sports&Outdoor'), ('HP', 'Home Products')], default='EL', max_length=25),
        ),
    ]
