# Generated by Django 4.2.4 on 2023-10-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('EL', 'Electronics'), ('AR', 'Arts&Crafts'), ('BE', 'Beauty'), ('CL', 'Clothings'), ('AC', 'Accessories'), ('TY', 'Toys&Games'), ('SP', 'Sports&Outdoor'), ('HP', 'Home Products')], default='EL', max_length=25),
        ),
    ]
