# Generated by Django 4.2.4 on 2024-08-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_time_added_reply_time_written_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='ordered_count',
            field=models.IntegerField(default=0),
        ),
    ]
