# Generated by Django 4.2.4 on 2023-10-20 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_seller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
