# Generated by Django 4.2.4 on 2024-08-13 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_seller_alter_reply_replier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='listed',
        ),
    ]
