# Generated by Django 4.2.4 on 2024-08-13 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_product_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_listed',
            field=models.BooleanField(default=False),
        ),
    ]
